//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleEncuesta
    {
        public int Id { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime Fechafinal { get; set; }
        public string Estado { get; set; }
        public int IdEncuesta { get; set; }
        public int IdArea { get; set; }
        public int IdCategoria { get; set; }
    
        public virtual Areas Areas { get; set; }
        public virtual Categorias Categorias { get; set; }
        public virtual Encuestas Encuestas { get; set; }
    }
}
